### ISSUE TITLE
Level 1: Pizza algorithm page 5 bug with duplicate blocks 

### ISSUE THREAD

**Issue by gol-like-soccer-goal** [IDEA-Lab-Vanderbilt-University/cml-narrative#62]
Couldn't recreate it perfectly... but when I dragged the blocks into a specific place on the left side of the screen, they duplicated. Can't figure out exactly where or how this is done. I attached a screenshot
![Screenshot 2024-10-07 at 1 57 39 PM](https://github.com/user-attachments/assets/e6d67e2c-8e6e-4e57-a751-1a7147a1d29a)

**Comment by gsteinLTU** [comment]
It was caused by dragging a block in a slot onto itself, this would result in the block being both sent back to the palette and its duplicate added to the slot.
